const data = [
  {
    image: {
      thumbnail: "assets/images/image-waffle-thumbnail.jpg",
      mobile: "assets/images/image-waffle-mobile.jpg",
      tablet: "assets/images/image-waffle-tablet.jpg",
      desktop: "assets/images/image-waffle-desktop.jpg",
    },
    name: "وافل با توت فرنگی",
    category: "وافل",
    price: 65000,
    id: 1,
  },
  {
    image: {
      thumbnail: "assets/images/image-creme-brulee-thumbnail.jpg",
      mobile: "assets/images/image-creme-brulee-mobile.jpg",
      tablet: "assets/images/image-creme-brulee-tablet.jpg",
      desktop: "assets/images/image-creme-brulee-desktop.jpg",
    },
    name: "کرم بروله وانیلی",
    category: "کرم بروله",
    price: 70000,
    id: 2,
  },
  {
    image: {
      thumbnail: "assets/images/image-macaron-thumbnail.jpg",
      mobile: "assets/images/image-macaron-mobile.jpg",
      tablet: "assets/images/image-macaron-tablet.jpg",
      desktop: "assets/images/image-macaron-desktop.jpg",
    },
    name: "مکرون میکس از هر 5 مدل",
    category: "مکرون",
    price: 80000,
    id: 3,
  },
  {
    image: {
      thumbnail: "assets/images/image-tiramisu-thumbnail.jpg",
      mobile: "assets/images/image-tiramisu-mobile.jpg",
      tablet: "assets/images/image-tiramisu-tablet.jpg",
      desktop: "assets/images/image-tiramisu-desktop.jpg",
    },
    name: "تیرامیسا کلاسیک",
    category: "تیرامیسا",
    price: 55000,
    id: 4,
  },
  {
    image: {
      thumbnail: "assets/images/image-baklava-thumbnail.jpg",
      mobile: "assets/images/image-baklava-mobile.jpg",
      tablet: "assets/images/image-baklava-tablet.jpg",
      desktop: "assets/images/image-baklava-desktop.jpg",
    },
    name: "باقلوا پسته ای",
    category: "باقلوا",
    price: 40000,
    id: 5,
  },
  {
    image: {
      thumbnail: "assets/images/image-meringue-thumbnail.jpg",
      mobile: "assets/images/image-meringue-mobile.jpg",
      tablet: "assets/images/image-meringue-tablet.jpg",
      desktop: "assets/images/image-meringue-desktop.jpg",
    },
    name: "پای مرنگ لیمو",
    category: "پای",
    price: 50000,
    id: 6,
  },
  {
    image: {
      thumbnail: "assets/images/image-cake-thumbnail.jpg",
      mobile: "assets/images/image-cake-mobile.jpg",
      tablet: "assets/images/image-cake-tablet.jpg",
      desktop: "assets/images/image-cake-desktop.jpg",
    },
    name: "کیک مخمل قرمز",
    category: "کیک",
    price: 45000,
    id: 7,
  },
  {
    image: {
      thumbnail: "assets/images/image-brownie-thumbnail.jpg",
      mobile: "assets/images/image-brownie-mobile.jpg",
      tablet: "assets/images/image-brownie-tablet.jpg",
      desktop: "assets/images/image-brownie-desktop.jpg",
    },
    name: "براونی کاراملی شور",
    category: "براونی",
    price: 45000,
    id: 8,
  },
  {
    image: {
      thumbnail: "assets/images/image-panna-cotta-thumbnail.jpg",
      mobile: "assets/images/image-panna-cotta-mobile.jpg",
      tablet: "assets/images/image-panna-cotta-tablet.jpg",
      desktop: "assets/images/image-panna-cotta-desktop.jpg",
    },
    name: "پاناکوتا وانیلی",
    category: "پاناکوتا",
    price: 65000,
    id: 9,
  },
];
export default data;